//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORK3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pavanEntities2 : DbContext
    {
        public pavanEntities2()
            : base("name=pavanEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Form> Forms { get; set; }

        public System.Data.Entity.DbSet<WORK3.ViewModels.Register> Registers { get; set; }

        public System.Data.Entity.DbSet<WORK3.ViewModels.Login> Logins { get; set; }
    }
}
